import type { NodeData } from "../contentData";

export const FRUITS_DATA: Record<string, NodeData> = {
  // ==========================================
  // F1: YOGA (FOUR PATHS) PARENT & CHILDREN
  // ==========================================
  yoga: {
    title: "Yoga (Four Paths)",
    code: "F1",
    question: "How do we channel our energy and intellect into liberation?",
    scope: "The classical four paths of Yoga represent different approaches to the spiritual search based on human temperament: action (Karma), knowledge (Jnana), devotion (Bhakti), and meditation (Raja).",
    subsections: [
      {
        title: "Karma Yoga (Action)",
        desc: "Transforming work into a selfless service to the cosmos, dissolving attachments to the outcomes of actions."
      },
      {
        title: "Jnana Yoga (Intellect)",
        desc: "The intellectual path of discrimination, separating the real from the unreal through study and inquiry."
      },
      {
        title: "Bhakti Yoga (Emotion)",
        desc: "Channelling devotion and emotional love toward the ultimate source of reality, dissolving the separate ego."
      },
      {
        title: "Raja Yoga (Concentration)",
        desc: "The royal path of mind control, concentration, and deep absorption (Samadhi) systematized by Patanjali."
      }
    ],
    thinkers: ["Swami Vivekananda", "Patanjali", "Krishna"],
    readings: [
      { title: "Jnana Yoga", author: "Swami Vivekananda" },
      { title: "The Bhagavad Gita", author: "Krishna" }
    ],
    bridge: {
      name: "Advaita Vedanta (R1)",
      path: "/roots/vedanta",
      desc: "Jnana Yoga is the direct path of Advaita, using the intellect to transcend the intellect."
    },
    childLinks: [
      { title: "Karma Yoga (Selfless Action)", path: "/fruit/yoga/karma", desc: "Purify the mind by relinquishing the fruits of action." },
      { title: "Jnana Yoga (Discrimination)", path: "/fruit/yoga/jnana", desc: "Trace the absolute distinction between the Seer and the Seen." },
      { title: "Bhakti Yoga (Devotional Love)", path: "/fruit/yoga/bhakti", desc: "Dissolve the ego in love and surrender to the Supreme." },
      { title: "Raja Yoga (Mind Control)", path: "/fruit/yoga/raja", desc: "Scientific mental restraint leading to deep absorption." }
    ]
  },
  "yoga/karma": {
    title: "Karma Yoga (Selfless Action)",
    code: "F1-A",
    question: "Can action be performed in absolute freedom without attachment to results?",
    scope: "Karma Yoga is the spiritual practice of selfless action. It involves performing duty without personal desire for praise, reward, or outcomes, transforming everyday tasks into a continuous process of self-transcendence.",
    subsections: [
      {
        title: "Nishkama Karma",
        desc: "Acting without seeking the fruits (rewards) of action. It neutralizes the psychological loop of craving (raga) and aversion (dvesha) generated by personal expectations."
      },
      {
        title: "Ego-less Instrumentality",
        desc: "Relinquishing the sense of personal 'doership'. The practitioner learns to view the body-mind as a temporary instrument through which cosmic forces express themselves."
      }
    ],
    thinkers: ["Swami Vivekananda", "Krishna"],
    readings: [
      { title: "Karma Yoga", author: "Swami Vivekananda" },
      { title: "The Bhagavad Gita", author: "Krishna" }
    ],
    bridge: {
      name: "Cognitive Science (B3)",
      path: "/branches/cognitive",
      desc: "Karma Yoga creates cognitive flow states, suppressing self-referential default network activity by focusing attention on the action itself."
    }
  },
  "yoga/jnana": {
    title: "Jnana Yoga (Path of Knowledge)",
    code: "F1-B",
    question: "How does the intellect discriminate between the eternal and the transient?",
    scope: "Jnana Yoga is the path of philosophical enquiry and discrimination (Viveka). It uses the intellect to analyze human experience, deconstruct the illusions of identity, and recognize the unborn Witness (Atman).",
    subsections: [
      {
        title: "Viveka (Discrimination)",
        desc: "The sharp, rational sorting of experience into two categories: the Real (unchanging witness consciousness) and the relative (changing objects, thoughts, and sensations)."
      },
      {
        title: "Vairagya (Dispassion)",
        desc: "The natural cooling of desire for temporary, object-based happiness once their transient, dependent nature is fully understood."
      }
    ],
    thinkers: ["Swami Vivekananda", "Adi Shankaracharya"],
    readings: [
      { title: "Jnana Yoga", author: "Swami Vivekananda" },
      { title: "Vivekachudamani", author: "Adi Shankaracharya" }
    ],
    bridge: {
      name: "Advaita Vedanta (R1)",
      path: "/roots/vedanta",
      desc: "Jnana Yoga is the direct contemplation of Vedanta's non-dual reality."
    }
  },
  "yoga/bhakti": {
    title: "Bhakti Yoga (Path of Devotion)",
    code: "F1-C",
    question: "Can human emotion be purified and directed toward the infinite source of all being?",
    scope: "Bhakti Yoga channels emotional energy—normally scattered among transient objects—toward the absolute ground of reality, personified as the Divine. The boundary of the ego is melted in the fire of unconditional love.",
    subsections: [
      {
        title: "Ishta Devata",
        desc: "Selecting a personal form or symbol of the Absolute (such as Krishna, Shiva, or Jesus) to focus devotion, transforming conceptual metaphysics into relational intimacy."
      },
      {
        title: "Prapatti (Total Surrender)",
        desc: "The final stage of devotion where the separate will is surrendered, dissolving all anxiety, worry, and egoic resistance into the absolute flow."
      }
    ],
    thinkers: ["Swami Vivekananda", "Ramakrishna Paramahamsa", "Krishna"],
    readings: [
      { title: "The Gospel of Sri Ramakrishna", author: "M. (Mahendranath Gupta)" }
    ],
    bridge: {
      name: "Esoteric Realities (R4)",
      path: "/roots/esoteric",
      desc: "Bhakti Yoga activates deep somatic and emotional states of unity, aligning with heart-centered mystical experiences."
    }
  },
  "yoga/raja": {
    title: "Raja Yoga (Path of Meditation)",
    code: "F1-D",
    question: "How does concentration lead to the direct perception of the Self?",
    scope: "Raja Yoga is the scientific path of mental restraint, structured as an eight-limbed discipline. It systematically quietens sensory inputs, breath, and thought-waves to reveal the underlying silent Seer.",
    subsections: [
      {
        title: "Chitta Vritti Nirodha",
        desc: "Patanjali's definition of Yoga: the cessation of the modifications (vibrations) of the mind-field. When the waves settle, the lake of consciousness shines clear."
      },
      {
        title: "The Eight Limbs",
        desc: "Yama and Niyama (ethics), Asana (posture), Pranayama (breath), Pratyahara (sensory withdrawal), Dharana (concentration), Dhyana (meditation), and Samadhi (absorption)."
      }
    ],
    thinkers: ["Patanjali", "Swami Vivekananda"],
    readings: [
      { title: "Raja Yoga", author: "Swami Vivekananda" },
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Neuroscience (B1)",
      path: "/branches/neuroscience",
      desc: "Raja Yoga practices directly regulate the central nervous system, shifting the brain into highly organized wave patterns and down-regulating default network centers."
    }
  },

  // ==========================================
  // F2: YOGA PRACTICES PARENT & CHILDREN
  // ==========================================
  "yoga-practices": {
    title: "Yoga Practices",
    code: "F2",
    question: "How do we prepare the body and mind for deep silence?",
    scope: "The somatic and energetic disciplines of classical yoga. These practices establish a stable physical base and regulate internal biological currents to remove distractions before meditation.",
    subsections: [
      {
        title: "Asana (Posture)",
        desc: "Establishing a physical posture that is completely stable and comfortable, removing somatic irritation from conscious awareness."
      },
      {
        title: "Pranayama (Breath Control)",
        desc: "Regulating the respiratory cycle to directly balance the sympathetic and parasympathetic nervous systems."
      },
      {
        title: "Dharana & Dhyana",
        desc: "Sustained focus and objectless absorption that eventually triggers the dissolution of the subject-object boundary."
      }
    ],
    thinkers: ["Patanjali"],
    readings: [
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Esoteric (R4)",
      path: "/roots/esoteric",
      desc: "These practices work directly with the subtle energy channels (Nadis) mapped in esoteric traditions."
    },
    childLinks: [
      { title: "Asana (Physical Stability)", path: "/fruit/yoga-practices/asana", desc: "Stabilize the somatic frame to eliminate physical noise." },
      { title: "Pranayama (Breath & Energy)", path: "/fruit/yoga-practices/pranayama", desc: "Balance the nervous system using deep energy regulation." },
      { title: "Dhyana (Absorption)", path: "/fruit/yoga-practices/dhyana", desc: "Transition from forced concentration to natural meditative absorption." }
    ]
  },
  "yoga-practices/asana": {
    title: "Asana (Physical Stability)",
    code: "F2-A",
    question: "How can the physical body be stabilized to minimize mental noise?",
    scope: "In classical yoga, Asana is defined not as dynamic gymnastics, but as a stable, comfortable seat ('Sthira-sukham asanam'). By aligning the skeletal frame, muscle activity is minimized, allowing the body to be forgotten.",
    subsections: [
      {
        title: "Sthira and Sukha",
        desc: "Sthira is firmness/stability; Sukha is comfort/ease. The posture must embody both. If there is pain, the mind remains trapped in somatic feedback loops."
      },
      {
        title: "Somatic De-concentration",
        desc: "Once the physical alignment is locked, the practitioner releases muscle tension, transferring weight to the skeletal support, quietening the motor cortex."
      }
    ],
    steps: [
      {
        title: "Establish the Base (Padmasana or Sukhasana)",
        desc: "Sit on a cushion with crossed legs, hips elevated higher than the knees. Keep the pelvis tilted slightly forward to maintain the natural curve of the lower back.",
        image: "/images/fruit/yoga_asana.png"
      },
      {
        title: "Align the Spine and Neck",
        desc: "Align the head directly over the heart, and the heart over the pelvis. Keep shoulders rolled back and relaxed. Gently tuck the chin in to align the cervical spine.",
        image: "/images/fruit/yoga_asana.png"
      },
      {
        title: "Stillness of the Gaze (Drishti)",
        desc: "Close the eyes gently or rest them at a 45-degree angle downward. Allow the eyes to rest in a soft, non-focusing gaze to quiet visual processing.",
        image: "/images/fruit/yoga_asana.png"
      }
    ],
    thinkers: ["Patanjali"],
    readings: [
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Cognitive Science (B3)",
      path: "/branches/cognitive",
      desc: "Asana aligns with Embodied Cognition: by keeping the physical body motionless, we suppress motor-sensory feedback loops that feed mental processing."
    }
  },
  "yoga-practices/pranayama": {
    title: "Pranayama (Breath Regulation)",
    code: "F2-B",
    question: "Can regulating the breath calm the nervous system and quiet the mind?",
    scope: "Pranayama regulates respiration to stabilize the life force (Prana). Because the respiratory cycle is directly linked to the autonomic nervous system, conscious control of the breath provides a remote control for the mind.",
    subsections: [
      {
        title: "Prana and Manas",
        desc: "Yogic psychology asserts that breath (Prana) and mind (Manas) are two sides of the same coin. When the breath is erratic, the mind vibrates; when the breath is steady, the mind becomes still."
      },
      {
        title: "Autonomic Balance",
        desc: "Slow, diaphragmatic breathing with extended exhalations stimulates the vagus nerve, initiating parasympathetic dominance and soothing cardiac distress."
      }
    ],
    steps: [
      {
        title: "Nadi Shodhana (Alternate Nostril Breathing)",
        desc: "Adopt Vishnu Mudra with the right hand. Close the right nostril with the thumb, inhale slowly through the left nostril. Close the left nostril, open the right, and exhale completely. Inhale right, close right, open left, and exhale left. Repeat for 5-10 cycles.",
        image: "/images/fruit/pranayama_breath.png"
      },
      {
        title: "Extended Exhalation (Pratiloma)",
        desc: "Inhale for a count of 4, hold gently for a count of 4, and exhale smoothly for a count of 8. The extended exhalation triggers a cooling, parasympathetic response.",
        image: "/images/fruit/pranayama_breath.png"
      }
    ],
    thinkers: ["Patanjali"],
    readings: [
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Neuroscience (B1)",
      path: "/branches/neuroscience",
      desc: "Pranayama alters arterial blood gases and heart rate variability, stimulating cortical areas related to autonomic control and focus."
    }
  },
  "yoga-practices/dhyana": {
    title: "Dhyana (Sustained Meditative Flow)",
    code: "F2-C",
    question: "What happens when the distinction between the meditator and the meditation dissolves?",
    scope: "Dhyana represents the transition from effort-based concentration (Dharana) to effortless, continuous attention. The observer begins to merge with the observed object, setting the stage for Samadhi.",
    subsections: [
      {
        title: "Dharana vs. Dhyana",
        desc: "Dharana is focusing the mind on a single point (breath, image, sound), characterized by frequent distractions and active correction. Dhyana occurs when the attention flows without interruption, like oil poured from one vessel to another."
      },
      {
        title: "Dissolution of Ego Boundaries",
        desc: "In deep Dhyana, the constant mental commentary of 'I am meditating' fades, leaving only the experience of the meditation itself."
      }
    ],
    steps: [
      {
        title: "Choose the Locus of Focus",
        desc: "Fix your attention on a single anchor, such as the pulse of the heart, the flow of breath, or the sound of a mantra. Rest your concentration there.",
        image: "/images/fruit/meditation_lotus.png"
      },
      {
        title: "Allow Distractions to Dissolve",
        desc: "When thoughts arise, do not fight them. Simply ignore them, allowing the attention to remain anchored until the thoughts settle on their own.",
        image: "/images/fruit/meditation_lotus.png"
      },
      {
        title: "Settle into Effortless Flow",
        desc: "As focus deepens, drop the effort of concentrating. Abide as the continuous flow of attention, where subject and object begin to blend.",
        image: "/images/fruit/meditation_lotus.png"
      }
    ],
    thinkers: ["Patanjali"],
    readings: [
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Philosophy of Mind (B2)",
      path: "/branches/philosophy",
      desc: "Dhyana is a state of pure phenomenal consciousness devoid of active, self-conscious access modeling."
    }
  },

  // ==========================================
  // F3: NON-DUAL REALIZATION
  // ==========================================
  "non-dual-realization": {
    title: "Non-Dual Realization",
    code: "F3",
    question: "What is the nature of unified, subject-object-free awareness?",
    scope: "Analyzing the state of unified awareness—often described as the absolute dissolution of the subject-object boundary. This node deconstructs this experience not as a mystical, divine achievement for the chosen few, but as a clean psychological and phenomenological shift in perception, comparing Vedanta's Jivanmukti and Buddhism's Nirvana as natural states of the human mind.",
    subsections: [
      {
        title: "Jivanmukti (Ego Dissolution)",
        desc: "The non-dual state of living freedom, where the mind operates and coordinates actions normally, but the self-referential ego-identity has dissolved, leaving only the spacious screen of silent, unattached witness consciousness."
      },
      {
        title: "Nirvana (Cessation of Representation)",
        desc: "In the Buddhist tradition, Nirvana is translated as the 'blowing out' of the fires of craving, aversion, and delusional self-models. Rather than a transcendental heaven, it represents the absolute cessation of the psychological loops that construct the separate ego."
      }
    ],
    thinkers: ["Adi Shankaracharya", "Gautama Buddha", "Ramana Maharshi", "Thomas Metzinger"],
    readings: [
      { title: "The Nature of Consciousness", author: "Rupert Spira" },
      { title: "The Ego Tunnel", author: "Thomas Metzinger" }
    ],
    bridge: {
      name: "Trunk Bridge",
      path: "/trunk",
      desc: "Non-Dual Realization is the baseline, objectless state of awareness mapped as the trunk of the tree."
    }
  },


  // ==========================================
  // F4: MODERN MEDICAL ACCEPTANCE (MEDICINE)
  // ==========================================
  medicine: {
    title: "Modern Medical Acceptance",
    code: "F4",
    question: "How does modern science apply contemplative tools to mental health?",
    scope: "The clinical adoption of non-dual and Buddhist tools, such as Mindfulness-Based Cognitive Therapy (MBCT) and Cognitive Behavioral Therapy (CBT).",
    subsections: [
      {
        title: "Mindfulness in Medicine",
        desc: "Kabat-Zinn's MBSR: stripping Buddhist vipassana of its religious language and using it to treat chronic pain, anxiety, and stress."
      },
      {
        title: "CBT and Ego Distancing",
        desc: "CBT teaches patients to observe their thoughts without identifying with them, a direct clinical application of the Witness methodology."
      }
    ],
    thinkers: ["Dr. Alok Kanojia", "Thomas Metzinger"],
    readings: [
      { title: "Full Catastrophe Living", author: "Jon Kabat-Zinn" }
    ],
    bridge: {
      name: "Cognitive Science (B3)",
      path: "/branches/cognitive",
      desc: "How do clinical mindfulness outcomes validate enactive and embodied cognitive models?"
    }
  },

  // ==========================================
  // F5: MEDITATION PORTAL (MEDITATION) PARENT & CHILDREN
  // ==========================================
  meditation: {
    title: "Meditation Portal",
    code: "F5",
    question: "Which meditation method fits your current state?",
    scope: "An overview of primary methods spanning Vedantic, Upanishadic, Buddhist, and classical Yogic traditions.",
    subsections: [
      {
        title: "Vedantic & Upanishadic Meditations",
        desc: "Focusing on the witness self (Sakshi) and the deconstruction of waking, dream, and sleep states."
      },
      {
        title: "Buddhist Vipassana & Zen",
        desc: "Direct observation of impermanence, selflessness (Anatta), and objectless sitting (Shikantaza)."
      },
      {
        title: "Classical Yoga Samyama",
        desc: "Patanjali's method of combining concentration, meditation, and total mental absorption."
      }
    ],
    thinkers: ["Gautama Buddha", "Rupert Spira", "Patanjali", "Adi Shankaracharya"],
    readings: [
      { title: "Being Aware of Being Aware", author: "Rupert Spira" }
    ],
    bridge: {
      name: "Direct Inquiry (R3)",
      path: "/roots/inquiry",
      desc: "Meditation is the direct practice that prepares the mind for deep Self-Inquiry."
    },
    childLinks: [
      { title: "Vedantic Meditation", path: "/fruit/meditation/vedantic", desc: "Abide as the silent, unattached witness of experience." },
      { title: "Upanishadic Contemplation", path: "/fruit/meditation/upanishadic", desc: "Deconstruct your identity using the waking, dream, and deep sleep states." },
      { title: "Buddhist Meditation (Vipassana/Zen)", path: "/fruit/meditation/buddhist", desc: "Observe bodily impermanence and practice objectless sitting." },
      { title: "Yoga Sutras Samyama", path: "/fruit/meditation/yogasutras", desc: "Master the integration of concentration and absolute mental absorption." }
    ]
  },
  "meditation/vedantic": {
    title: "Vedantic Meditation (I Am Witness)",
    code: "F5-A",
    question: "Can we remain as the silent Seer of all mental fluctuations?",
    scope: "Vedantic meditation is the practice of abiding as the Seer (Drk) rather than identifying with the seen (Drsya). By turning attention away from thoughts and resting in bare awareness, the separate self dissolves.",
    subsections: [
      {
        title: "Drk-Drsya discrimination",
        desc: "Everything you can observe—the room, your body, your thoughts, your emotions—is the Seen. You are the Seer. Since you can observe your thoughts, you cannot be your thoughts."
      },
      {
        title: "Abidance in Awareness",
        desc: "Letting go of focusing on any particular object. The practitioner rests attention on the light of awareness itself, which is open, still, and contentless."
      }
    ],
    steps: [
      {
        title: "Observe the Stream of Thought",
        desc: "Close your eyes. Let thoughts, sensations, and sounds arise. Sit in silence without reacting, judging, or trying to change them.",
        image: "/images/fruit/meditation_lotus.png"
      },
      {
        title: "Inquire into the Witness",
        desc: "Gently turn the spotlight of attention back on itself. Ask: 'Who is witnessing this thought?' Rest in the silent space that remains prior to thought.",
        image: "/images/fruit/meditation_lotus.png"
      }
    ],
    thinkers: ["Adi Shankaracharya", "Nisargadatta Maharaj", "Rupert Spira"],
    readings: [
      { title: "Drg-Drk-Viveka", author: "Adi Shankaracharya" },
      { title: "Being Aware of Being Aware", author: "Rupert Spira" }
    ],
    bridge: {
      name: "Advaita Vedanta (R1)",
      path: "/roots/vedanta",
      desc: "Directly realizes the core teaching of Advaita that the Seer and the Seen are distinct."
    }
  },
  "meditation/upanishadic": {
    title: "Upanishadic Contemplation (Contemplation of OM)",
    code: "F5-B",
    question: "How do the states of waking, dreaming, and deep sleep point to the stateless Absolute?",
    scope: "Based on the Mandukya Upanishad, this contemplation deconstructs personal identity by analyzing the three states of human experience to reveal the fourth (Turiya)—the silent witness consciousness.",
    subsections: [
      {
        title: "The Three States (A-U-M)",
        desc: "'A' represents the waking state (Vaisvanara); 'U' represents the dream state (Taijasa); 'M' represents deep sleep (Prajna). Each state has its own subject and object, but all are temporary."
      },
      {
        title: "Turiya (The Silence)",
        desc: "Turiya is the silent awareness that witnesses all three states. It is represented by the silence that follows the chanting of the syllables A-U-M."
      }
    ],
    steps: [
      {
        title: "Deconstruct the Waking State",
        desc: "Contemplate the waking world and your waking self. Realize that this state is temporary—it disappears completely when you fall asleep.",
        image: "/images/fruit/upanishadic_om.png"
      },
      {
        title: "Deconstruct the Dream State",
        desc: "Contemplate the dream state. The mind creates its own space, time, and objects, which seem completely real until you wake up. Who is the dreamer?",
        image: "/images/fruit/upanishadic_om.png"
      },
      {
        title: "Contemplate Deep Sleep",
        desc: "Contemplate deep sleep. There are no thoughts, no world, and no ego, yet you wake up and say 'I slept peacefully.' Who was present in that silence?",
        image: "/images/fruit/upanishadic_om.png"
      },
      {
        title: "Abide as Turiya",
        desc: "Recognize that you are the changeless witness (Turiya) that runs through all three states, symbolized by the silence that remains after the sound of OM.",
        image: "/images/fruit/upanishadic_om.png"
      }
    ],
    thinkers: ["Swami Sarvapriyananda", "Adi Shankaracharya"],
    readings: [
      { title: "Mandukya Upanishad with Gaudapada's Karika", author: "Swami Nikhilananda trans." }
    ],
    bridge: {
      name: "Philosophy of Mind (B2)",
      path: "/branches/philosophy",
      desc: "This deconstruction of identity mirrors modern debates around neural correlates of sleep and minimal selfhood."
    }
  },
  "meditation/buddhist": {
    title: "Buddhist Meditation (Vipassana & Zen)",
    code: "F5-C",
    question: "How does observing the impermanence of sensations dissolve the illusion of self?",
    scope: "Vipassana (insight) and Shikantaza (just sitting) are core Buddhist meditations designed to directly observe the three marks of existence: impermanence (Anicca), selflessness (Anatta), and unsatisfactoriness (Dukkha).",
    subsections: [
      {
        title: "Vipassana (Insight)",
        desc: "Systematic scanning of physical sensations to observe their changing, rising-and-falling nature, breaking down the illusion of a solid body and self."
      },
      {
        title: "Shikantaza (Zen Sitting)",
        desc: "Objectless sitting ('just sitting'). No anchors, no visualization, no mantras. The practitioner sits as open, silent awareness, allowing the universe to flow."
      }
    ],
    steps: [
      {
        title: "Focus on the Breath (Anapana)",
        desc: "Anchor attention at the entrance of the nostrils. Observe the natural, touch-sensation of the breath coming in and going out.",
        image: "/images/fruit/zen_enso.png"
      },
      {
        title: "Somatic Scanning (Vipassana)",
        desc: "Move attention systematically from head to toe. Note any sensation (heat, cold, itching, pulsing) as temporary, arising and dissolving.",
        image: "/images/fruit/zen_enso.png"
      },
      {
        title: "Rest in Just Sitting (Shikantaza)",
        desc: "Release all focus. Open the fields of hearing and body. Just sit as the space in which all events occur.",
        image: "/images/fruit/zen_enso.png"
      }
    ],
    thinkers: ["Gautama Buddha"],
    readings: [
      { title: "Dhammapada", author: "Gautama Buddha" }
    ],
    bridge: {
      name: "Cognitive Science (B3)",
      path: "/branches/cognitive",
      desc: "Vipassana deconstructs the bodily self-model (interoception) and correlates with DMN down-regulation."
    }
  },
  "meditation/yogasutras": {
    title: "Yoga Sutras Samyama",
    code: "F5-D",
    question: "How does the integration of concentration, meditation, and absorption dissolve mental limits?",
    scope: "Samyama is the combined practice of Dharana (concentration), Dhyana (meditation), and Samadhi (absorption) on a single object, as defined in Patanjali's Yoga Sutras.",
    subsections: [
      {
        title: "The Three Pillars of Samyama",
        desc: "Dharana is fixing attention on an object; Dhyana is the effortless flow of attention; Samadhi is when the self dissolves and only the object remains."
      },
      {
        title: "Integration (Samyama)",
        desc: "When these three stages are applied in rapid succession to a single object, the boundaries between observer, observing, and observed collapse."
      }
    ],
    steps: [
      {
        title: "Select the Meditative Anchor",
        desc: "Focus attention on a single subtle object, such as the heart center (Anahata chakra) or the root of the tongue.",
        image: "/images/fruit/meditation_lotus.png"
      },
      {
        title: "Transition to Samadhi",
        desc: "Allow concentration to become continuous (Dhyana) until your sense of self vanishes entirely into the object of meditation (Samadhi).",
        image: "/images/fruit/meditation_lotus.png"
      }
    ],
    thinkers: ["Patanjali"],
    readings: [
      { title: "Yoga Sutras of Patanjali", author: "Patanjali" }
    ],
    bridge: {
      name: "Quantum Mind (B4)",
      path: "/branches/quantum",
      desc: "Patarjali's descriptions of Samyama describe a unified, non-local entanglement between the observer and the observed."
    }
  },

  // ==========================================
  // F6: PSYCHEDELICS & MIND
  // ==========================================
  "psychedelics": {
    title: "Psychedelics & Consciousness",
    code: "F6",
    question: "Can chemical intervention trigger ego dissolution?",
    warning: "WARNING: The following information is for educational, philosophical, and scientific purposes only. Psychedelics are powerful psychoactive compounds that carry significant psychological risks, particularly for individuals with a personal or family history of psychosis, schizophrenia, or severe mood disorders. The use of these substances should only occur under professional clinical guidance.",
    scope: "Exploring the intersection of psychopharmacology, neuroscience, and non-dual phenomenology. This node details the therapeutic benefits of psychedelics (psilocybin, DMT, LSD) for mental health illnesses, the neural mechanism of serotonin 5-HT2A receptor agonism, and how chemical states induce temporary 'ego-death' experiences that mirror classical non-dual realization.",
    subsections: [
      {
        title: "Clinical Therapeutics (Mental Health)",
        desc: "Clinical trials from institutions like Johns Hopkins and Imperial College London show that substances like psilocybin and DMT can cause rapid, sustained reductions in treatment-resistant depression, anxiety, and PTSD. By promoting neuroplasticity (synaptogenesis) and increasing brain connectivity, they help break rigid, maladaptive cognitive loops."
      },
      {
        title: "Neurological Mechanism (Serotonin & DMN)",
        desc: "Classic psychedelics act primarily as agonists at the 5-HT2A serotonin receptor. This stimulation leads to a dramatic suppression of the Default Mode Network (DMN)—the brain's self-referential 'ego center'. As the DMN's gating mechanism shuts down, regions of the brain that do not normally talk to each other communicate directly, creating a highly integrated global workspace."
      },
      {
        title: "Ego-Death & Non-Duality",
        desc: "At high doses, particularly with DMT or high-dose psilocybin, the brain's predictive self-model dissolves completely. The subjective boundary between 'self' and 'universe' collapses (ego-death), leading to a temporary state of raw, undivided awareness that closely aligns with the insights of Non-Dual Realization and deep meditation."
      }
    ],
    thinkers: ["David Chalmers", "Thomas Metzinger", "Anil Seth"],
    readings: [
      { title: "How to Change Your Mind", author: "Michael Pollan" },
      { title: "The Ego Tunnel", author: "Thomas Metzinger" }
    ],
    bridge: {
      name: "Neuroscience (B1)",
      path: "/branches/neuroscience",
      desc: "Psychedelic research bridges directly to the neuroscience of the Default Mode Network and the Hard Problem of Consciousness."
    }
  },


  // ==========================================
  // F7: GUIDED SELF-INQUIRY (SELF-INQUIRY) PARENT & CHILDREN
  // ==========================================
  "self-inquiry": {
    title: "Guided Self-Inquiry",
    code: "F7",
    question: "Can we trace the sense of being back to its source right now?",
    scope: "Experiential exercises designed to direct attention back to its source—the bare sense of existence prior to thoughts, memories, and identity.",
    subsections: [
      {
        title: "Atma Vichara (Who Am I?)",
        desc: "Tracing the root 'I-thought' back to its silent source, popularized by Sri Ramana Maharshi."
      },
      {
        title: "Neti Neti (Negation)",
        desc: "Systematically negating identifying with transient objects (body, mind, roles) to isolate the subject."
      },
      {
        title: "The Witness Inquiry",
        desc: "Recognizing the silent space of awareness which remains untouched by the content of experience."
      }
    ],
    thinkers: ["Ramana Maharshi", "Rupert Spira", "Nisargadatta Maharaj"],
    readings: [
      { title: "Who Am I?", author: "Ramana Maharshi" },
      { title: "I Am That", author: "Nisargadatta Maharaj" }
    ],
    bridge: {
      name: "Direct Inquiry (R3)",
      path: "/roots/inquiry",
      desc: "This represents the active contemplative implementation of the Inquiry root."
    },
    childLinks: [
      { title: "Who Am I? (Atma Vichara)", path: "/fruit/self-inquiry/who-am-i", desc: "Trace the root 'I-thought' back to its source." },
      { title: "Neti Neti (Negation)", path: "/fruit/self-inquiry/neti-neti", desc: "Negate identification with bodily and mental appearances." },
      { title: "The Witness Inquiry", path: "/fruit/self-inquiry/witness", desc: "Isolate the silent screen of awareness from the movie of life." }
    ]
  },
  "self-inquiry/who-am-i": {
    title: "Who Am I? (Atma Vichara)",
    code: "F7-A",
    question: "Who is the one experiencing this moment?",
    scope: "Self-Inquiry (Atma Vichara) is the direct path popularized by Ramana Maharshi. It involves tracing the sense of 'I' back to its source.",
    warning: "⚠️ CAUTION: Intense self-inquiry can cause feelings of derealization (the world feeling unreal) or depersonalization (feeling detached from your body). If you have a history of trauma, clinical anxiety, or mental health struggles, practice under the guidance of an experienced teacher or pause if distress arises.",
    steps: [
      {
        title: "Step 1: Relaxing into Presence",
        desc: "Settle into your body. Notice the sounds, sensations, and thoughts. Realize that you are aware of them.",
        image: "/images/fruit/who_am_i_heart.png"
      },
      {
        title: "Step 2: Who is Aware?",
        desc: "Ask: 'Who is the one aware of these thoughts?' Notice the immediate silence that follows the question. Abide in that gap.",
        image: "/images/fruit/who_am_i_heart.png"
      },
      {
        title: "Step 3: Tracing the 'I-thought'",
        desc: "When a new thought arises, ask: 'To whom does this thought arise?' The answer is: 'To me.' Then ask: 'Who am I? Where does this I arise?' Trace it back to silent awareness.",
        image: "/images/fruit/who_am_i_heart.png"
      }
    ],
    thinkers: ["Ramana Maharshi", "Rupert Spira"],
    readings: [
      { title: "Who Am I?", author: "Ramana Maharshi" }
    ],
    bridge: {
      name: "Direct Inquiry (R3)",
      path: "/roots/inquiry",
      desc: "Atma Vichara is the ultimate practical implementation of the inquiry roots."
    }
  },
  "self-inquiry/neti-neti": {
    title: "Neti Neti Contemplation",
    code: "F7-B",
    question: "What remains when you negate everything you are aware of?",
    scope: "Neti Neti ('not this, not this') is a Vedantic process of negation. By recognizing that you are the subject witnessing objects, you realize you cannot be any object you observe.",
    warning: "⚠️ CAUTION: Relentless negation can lead to ego-dissolution states that may feel disorienting. Proceed gently and anchor yourself in your daily life if feelings of groundlessness become uncomfortable.",
    steps: [
      {
        title: "Step 1: Not the Body",
        desc: "Observe the physical body. Since you can observe the body, you are the observer, not the body itself.",
        image: "/images/fruit/neti_neti_negation.png"
      },
      {
        title: "Step 2: Not the Mind",
        desc: "Observe your thoughts, emotions, and memories. Since you can watch them come and go, you are the observer, not the thoughts themselves.",
        image: "/images/fruit/neti_neti_negation.png"
      },
      {
        title: "Step 3: Abiding as the Remainder",
        desc: "Once body, mind, senses, and roles are negated, what is left? Abide as the contentless witness consciousness.",
        image: "/images/fruit/neti_neti_negation.png"
      }
    ],
    thinkers: ["Adi Shankaracharya", "Nisargadatta Maharaj"],
    readings: [
      { title: "Vivekachudamani", author: "Adi Shankaracharya" }
    ],
    bridge: {
      name: "Philosophy of Mind (B2)",
      path: "/branches/philosophy",
      desc: "Neti Neti deconstructs the physicalist self-model layer by layer, separating subject and representation."
    }
  },
  "self-inquiry/witness": {
    title: "Witness Consciousness Inquiry",
    code: "F7-C",
    question: "Is the witness of thoughts affected by the thoughts it witnesses?",
    scope: "An inquiry focusing on the nature of the witness (Sakshi). It explores the stillness, purity, and unattached nature of awareness.",
    steps: [
      {
        title: "Step 1: Discovering Stillness",
        desc: "Watch a stressful thought arise. Notice that the screen of awareness on which the thought appears is completely still and unharmed.",
        image: "/images/fruit/self_inquiry_witness.png"
      }
    ],
    thinkers: ["Nisargadatta Maharaj", "Ramana Maharshi"],
    readings: [
      { title: "I Am That", author: "Nisargadatta Maharaj" }
    ],
    bridge: {
      name: "Quantum Mind (B4)",
      path: "/branches/quantum",
      desc: "The witness mimics the observer who measures quantum states without being modified by them."
    }
  },

  // ==========================================
  // F8: PLAYLISTS
  // ==========================================
  playlists: {
    title: "Video Playlists",
    code: "F8",
    question: "What are the key audio-visual lectures and debates to watch?",
    scope: "Curated lists of YouTube lectures, dialogues, and scientific debates on consciousness.",
    subsections: [
      {
        title: "Vedanta Classics",
        desc: "Sarvapriyananda's Mandukya Upanishad lectures, exploring the three states in detail."
      },
      {
        title: "Science-Philosophy Debates",
        desc: "Bernardo Kastrup vs. physicalist philosophers, Donald Hoffman's visual interface talks."
      }
    ],
    thinkers: ["Swami Sarvapriyananda", "Donald Hoffman", "Bernardo Kastrup"],
    readings: [
      { title: "Video Playlists Archive", author: "Tree of Truth Editors" }
    ],
    bridge: {
      name: "Trunk Bridge",
      path: "/trunk",
      desc: "Playlists help visualize the convergence between science and wisdom."
    }
  },

  // ==========================================
  // F9: JOURNALING
  // ==========================================
  journaling: {
    title: "Journaling Prompts",
    code: "F9",
    question: "What questions can you write about to dismantle your ego assumptions?",
    scope: "Writing prompts designed to trigger self-inquiry and phenomenological reduction.",
    subsections: [
      {
        title: "Subtracting Identity",
        desc: "Write: 'What remains when I subtract my name, my memories, and my language?' Observe what is felt in your experience during this subtraction."
      },
      {
        title: "The Womb & Sleep Prompts",
        desc: "Write: 'If I was born senseless, what would I be?' and 'Who was present in deep sleep last night?'"
      }
    ],
    thinkers: ["Ramana Maharshi", "Dan Zahavi"],
    readings: [
      { title: "Journaling Prompts Archive", author: "Tree of Truth Editors" }
    ],
    bridge: {
      name: "Direct Inquiry (R3)",
      path: "/roots/inquiry",
      desc: "Journaling is a reflective method to solidify the insights of Direct Inquiry."
    }
  }
};
